#!/bin/bash
# save this file as tailc then
# run as: $ tailc log Words_to_highlight
file=$1

if [[ -n "$2" ]]; then
    color='
    // {print "\033[37m" $0 "\033[39m"}
    /(STATUS:PASS)/ {print "\033[1;32m" $0 "\033[0m"} 
    /(STATUS:ERROR|STATUS:FAIL)/ {print "\033[1;31m" $0 "\033[0m"}
    /('$2')/ {print "\033[1;32m" $0 "\033[0m"}
    '
else
    color='
    // {print "\033[37m" $0 "\033[39m"}
    /(STATUS:PASS)/ {print "\033[1;32m" $0 "\033[0m"} 
    /(STATUS:ERROR|STATUS:FAIL)/ {print "\033[1;31m" $0 "\033[0m"} 
    '
fi

tail -f $file | awk "$color"

# Colors
# 30 - black   34 - blue          40 - black    44 - blue
# 31 - red     35 - magenta       41 - red      45 - magenta
# 32 - green   36 - cyan          42 - green    46 - cyan
# 33 - yellow  37 - white         43 - yellow   47 - white
